In [58]:
import pandas as pd
import numpy as np

In [59]:
credits = pd.read_csv("C:\\Users\\GauravMathur\\Desktop\\Recommendation System\\tmdb_5000_credits.csv")
movies = pd.read_csv("C:\\Users\\GauravMathur\\Desktop\\Recommendation System\\tmdb_5000_movies.csv")

In [60]:
credits_rename= credits.rename(index= str, columns = {'movie_id':'id'})

In [61]:
movies_merge = movies.merge(credits_rename , on ='id')
movies_merge.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [62]:
movies_merge = movies_merge.drop(columns=['homepage','status', 'title_x','title_y','production_companies'])

In [63]:
R = movies_merge['vote_average']
v = movies_merge['vote_count']
C = movies_merge['vote_average'].mean()
m = movies_merge['vote_count'].quantile(0.70)

In [65]:
movies_merge['weighted_average'] = ((R*v) + (C*m)/(v+m))

In [67]:
movies_merge_sorted = movies_merge.sort_values('weighted_average',ascending= False)

In [68]:
movies_merge_sorted[['original_title', 'weighted_average']].head(10)

              original_title  weighted_average
96                 Inception     111391.446951
65           The Dark Knight      98416.681296
95              Interstellar      88023.009185
16              The Avengers      87142.686441
0                     Avatar      84960.285886
788                 Deadpool      81363.305766
287         Django Unchained      78772.531419
662               Fight Club      78128.254168
94   Guardians of the Galaxy      76962.142880
634               The Matrix      70365.673056

In [70]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
movie_scaled = scaler.fit_transform(movies_merge[['weighted_average','popularity']])
movie_normalized = pd.DataFrame(movie_scaled,columns= ['weighted_average','popularity'])
movie_normalized.head()

   weighted_average  popularity
0          0.762705    0.171815
1          0.278714    0.158846
2          0.252550    0.122635
3          0.621265    0.128272
4          0.116278    0.050169

In [73]:
movies_merge[['normalized_average', 'normalized_popularity']] = movie_normalized

In [74]:
movies_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   budget                 4803 non-null   int64
 1   genres                 4803 non-null   object
 2   id                     4803 non-null   int64
 3   keywords               4803 non-null   object
 4   original_language      4803 non-null   object
 5   original_title         4803 non-null   object
 6   overview               4800 non-null   object
 7   popularity             4803 non-null   float64
 8   production_countries   4803 non-null   object
 9   release_date           4802 non-null   object
 10  revenue                4803 non-null   int64
 11  runtime                4801 non-null   float64
 12  spoken_languages       4803 non-null   object
 13  tagline                3959 non-null   object
 14  vote_average           4803 non-null   float64
 15  vote_count             4803 non-null   int64
 16  cast                   4803 non-null   object
 17  crew                   4803 non-null   object
 18  weighted_average       4803 non-null   float64
 19  normalized_average     4803 non-null   float64
 20  normalized_popularity  4803 non-null   float64
dtypes: float64(6), int64(4), object(11)
memory usage: 825.5+ KB

In [77]:
movies_merge['score'] = (movies_merge['normalized_average']*0.5 + movies_merge['normalized_popularity']*0.5)

In [80]:
movies_merge_sorted = movies_merge.sort_values('score',ascending = False)
movies_merge_sorted[['original_title', 'score']].head(20)

                                         original_title     score
95                                         Interstellar  0.808682
788                                            Deadpool  0.659051
546                                             Minions  0.631296
94                              Guardians of the Galaxy  0.620181
96                                            Inception  0.595699
127                                  Mad Max: Fury Road  0.552651
65                                      The Dark Knight  0.548728
28                                       Jurassic World  0.491817
16                                         The Avengers  0.473637
0                                                Avatar  0.467260
662                                          Fight Club  0.434490
287                                    Django Unchained  0.400472
262   The Lord of the Rings: The Fellowship of the Ring  0.391416
1881                           The Shawshank Redemption  0.391133
199   Pirates of the Caribbean: The Curse of the Bla...  0.390448
3232                                       Pulp Fiction  0.383347
634                                          The Matrix  0.375405
3                                 The Dark Knight Rises  0.374769
809                                        Forrest Gump  0.370642
329       The Lord of the Rings: The Return of the King  0.363783